#ifndef GUARD_CONSTANTS_POKEGOTCHI_H
#define GUARD_CONSTANTS_POKEGOTCHI_H

#define FEED_FOOD_KEY_NONE      0
#define FEED_FOOD_KEY_LEAF      1
#define FEED_FOOD_KEY_HOT_DOG   2
#define FEED_FOOD_KEY_POKEBLOCK 3
#define FEED_FOOD_KEY_EGG       4
#define FEED_FOOD_KEY_PECHA     5
#define FEED_FOOD_KEY_ICE_CREAM 6
#define FEED_FOOD_KEY_DONUT     7
#define FEED_FOOD_KEY_SNACK_4   8

#endif // GUARD_CONSTANTS_POKEGOTCHI_H
